[window]
title = "Console"
dynamic_title=false
decorations = "None"
opacity = 0.9
padding = {x=10,y=10}

[font]
normal = { family = "Fira Code", style = "Regular" }
size=10
builtin_box_drawing = true

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }

[mouse]
hide_when_typing = true
# Colors (Gruvbox dark)

[colors.primary]
background = '#000000'
foreground = '#E6E6E6'

[colors.normal]
black = '#000000'
red = '#FF4C4C'
green = '#33FF99'
yellow = '#FFD93D'
blue = '#339CFF'
magenta = '#C873FF'
cyan = '#33FFF0'
white = '#E6E6E6'

[colors.bright]
black = '#4D4D4D'
red = '#FF6666'
green = '#66FFB2'
yellow = '#FFE866'
blue = '#66B3FF'
magenta = '#D78BFF'
cyan = '#66FFF5'
white = '#FFFFFF'
